set lines 1000
break on report
compute sum of AUTOEXTEND_MAX_MB on report
compute sum of CURR_ALLOC_MB on report
compute sum of CURR_FREE_MB on report
compute sum of AUTOEXTEND_FREE_MB on report

select tablespace_name,AUTOEXTEND_MAX_MB,CURR_ALLOC_MB,CURR_FREE_MB,
       decode(sign(AUTOEXTEND_MAX_MB-CURR_ALLOC_MB),1,AUTOEXTEND_MAX_MB-CURR_ALLOC_MB,0)+CURR_FREE_MB AUTOEXTEND_FREE_MB,
       round(100*CURR_FREE_MB/CURR_ALLOC_MB) CURR_FREE_PERC,
       round(100*(decode(sign(AUTOEXTEND_MAX_MB-CURR_ALLOC_MB),1,AUTOEXTEND_MAX_MB-CURR_ALLOC_MB,0)+CURR_FREE_MB)/
 decode(sign(AUTOEXTEND_MAX_MB-CURR_ALLOC_MB),1,AUTOEXTEND_MAX_MB,CURR_ALLOC_MB)) 
AUTOEXENTD_FREE_PERC
  from
(
SELECT TABLESPACE_NAME,SUM(AUTOEXTEND_MAX_MB) AUTOEXTEND_MAX_MB,SUM(ALLOC_MB) CURR_ALLOC_MB, ROUND(SUM(CURR_FREE_MB)) CURR_FREE_MB
  FROM
(
select tablespace_name,sum(decode(autoextensible,'YES',MAXBYTES,BYTES))/1024/1024 AUTOEXTEND_MAX_MB, SUM(BYTES)/1024/1024 ALLOC_MB, 0 USED_MB, 0 CURR_FREE_MB
  FROM DBa_DATA_FILES
 GROUP BY TABLESPACE_NAME
UNION ALL
select tablespace_name,sum(decode(autoextensible,'YES',MAXBYTES,BYTES))/1024/1024 AUTOEXTEND_MAX_MB, SUM(BYTES)/1024/1024 ALLOC_MB, 0 USED_MB, 0 CURR_FREE_MB
  FROM DBa_TEMP_FILES
 GROUP BY TABLESPACE_NAME
union all 
SELECT TABLESPACE_NAME,0,0,0,SUM(BYTES)/1024/1024 CURR_FREE_MB
  FROM DBA_FREE_SPACE
 GROUP BY TABLESPACE_NAME
UNION ALL
SELECT TABLESPACE_NAME,0,0,0,SUM(BYTES_FREE)/1024/1024 CURR_FREE_MB
  FROM V$TEMP_SPACE_HEADER
 GROUP BY TABLESPACE_NAME
)
 GROUP BY TABLESPACE_NAME
)
order by 6 desc; 
